Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'Rakefile'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'test/test_helper.rb'
    - 'config/puma.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/bower_rails.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/new_framework_defaults.rb'
    - 'app/helpers/application_helper.rb'
    - 'db/**/*'
    - 'bin/*'
    - 'lib/tasks/*'
  TargetRubyVersion: 2.3
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Date:
  Enabled: false
ParenthesesAsGroupedExpression:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Rails/FindEach:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: false
